name = "streamfilter"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "streamfilter-ranking"
database_id = "9dc1720d-c637-42c4-b954-881db27eedfd"

[[analytics_engine_datasets]]
binding = "AE"
dataset = "video_plays"
